#!/bin/bash

# Pastikan builder multiarch aktif
docker buildx use multiarch-builder 2>/dev/null || docker buildx create --name multiarch-builder --use

# Build and Push multi-arch (linux/amd64, linux/arm64) ke Docker Hub
docker buildx build \
  --platform linux/amd64,linux/arm64 \
  -t dhewe/notifierserver:1.1.0 \
  -t dhewe/notifierserver:latest \
  --push .
