version: '3.8'

networks:
  docker1:
    external: true

services:
  notifierserver:
    container_name: notifierserver
    image: notifierserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8989
    ports:
      - "8989:8989"
    networks:
      - docker1
    restart: unless-stopped
