version: '3.8'


networks:
  dev:
    external: true


services:
  notifierserver:
    container_name: notifierserver
    image: notifierserver
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8989
    ports:
      - "${PORT:-8989}:${PORT:-8989}"
    networks:
      - dev
    restart: unless-stopped
